<a href="https://colab.research.google.com/github/StatsAI/NLP/blob/main/Faker_Test_SQL_Database_Generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.10/dist-packages (24.7.1)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)

In [ ]:
from faker import Faker
from sqlalchemy import create_engine, Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import pandas as pd

# Configure SQLAlchemy
engine = create_engine('sqlite:///customers.db')  # Adjust connection string as needed
Base = declarative_base()

# Define Customer model
class Customer(Base):
    __tablename__ = 'customers'

    customer_id = Column(Integer, primary_key=True)
    first_name = Column(String(255))
    last_name = Column(String(255))
    email = Column(String(255))
    phone_number = Column(String(20))
    address_line_1 = Column(String(255))
    address_line_2 = Column(String(255))
    city = Column(String(255))
    state = Column(String(50))
    postal_code = Column(String(20))
    country = Column(String(50))

# Create tables (drop existing if needed)
Base.metadata.reflect(engine)
if "customers" in Base.metadata.tables:
    Base.metadata.tables["customers"].drop(engine)
Base.metadata.create_all(engine)

# Generate fake data
fake = Faker()
session = sessionmaker(bind=engine)()

for _ in range(10):
    customer = Customer(
        first_name=fake.first_name(),
        last_name=fake.last_name(),
        email=fake.email(),
        phone_number=fake.phone_number(),
        address_line_1=fake.street_address(),
        address_line_2=fake.secondary_address(),
        city=fake.city(),
        state=fake.state_abbr(),
        postal_code=fake.postcode(),
        country=fake.country(),
    )
    session.add(customer)

session.commit()

# Query data to pandas dataframe
session = sessionmaker(bind=engine)()
customers_df = pd.read_sql_table("customers", engine)

# Print dataframe (verification)
#print("Customer Data (pandas dataframe):")
customers_df

#session.close()

<ipython-input-34-439973838afa>:9: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

,customer_id,first_name,last_name,email,phone_number,address_line_1,address_line_2,city,state,postal_code,country
0,1,Donna,Vasquez,singhsamantha@example.org,001-635-457-8710x3194,302 Ford Trail Apt. 396,Apt. 116,Hayesmouth,NY,60935,Antigua and Barbuda
1,2,Nicole,Ryan,pgreen@example.com,404-366-8681x711,586 Chen Plaza,Apt. 181,Hinesburgh,GA,84162,United Arab Emirates
2,3,Sarah,Mclean,brownnicholas@example.org,817.599.5824x309,80647 Ruiz Plains,Apt. 511,Petersberg,FM,80309,Sierra Leone
3,4,Kenneth,Mendez,usmith@example.com,+1-727-979-5792x294,470 Lauren View Apt. 644,Suite 226,Myersport,TX,62161,Trinidad and Tobago
4,5,Lauren,Fisher,gtorres@example.net,+1-272-307-3269x09279,794 Thomas Way Suite 835,Apt. 565,Hillmouth,MP,73250,Solomon Islands
5,6,Diane,Hernandez,douglasaaron@example.com,+1-997-309-1499,8712 Jason Villages Suite 656,Apt. 366,Jacksonmouth,UT,06362,Micronesia
6,7,Daniel,Clay,morrisrhonda@example.net,(909)750-1697,232 Crawford Trail Apt. 608,Apt. 599,Wilsontown,MA,16605,United States of America
7,8,Victoria,Ramirez,kimberlyjones@example.net,231-412-3633,83970 Kevin Union Apt. 997,Apt. 742,Jessicaton,VA,16817,Turkmenistan
8,9,Richard,Jackson,reedstephanie@example.net,+1-558-556-9450x5277,69561 Jonathan Mall,Apt. 525,Rebeccaview,HI,63844,Kazakhstan
9,10,Nicole,James,jeffrey37@example.net,(683)692-1045x58909,583 Shannon Neck,Suite 939,Houstonhaven,ND,84652,Mauritius

In [ ]:
from faker import Faker
from sqlalchemy import create_engine, Column, Numeric, Integer, String, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import pandas as pd
import random


# Configure SQLAlchemy
engine = create_engine('sqlite:///customers.db')  # Adjust connection string as needed
Base = declarative_base()

# Define Customer model
class Customer(Base):
    __tablename__ = 'customers'

    customer_id = Column(Integer, primary_key=True)
    first_name = Column(String(255))
    last_name = Column(String(255))
    email = Column(String(255))
    phone_number = Column(String(20))
    address_line_1 = Column(String(255))
    address_line_2 = Column(String(255))
    city = Column(String(255))
    state = Column(String(50))
    postal_code = Column(String(20))
    country = Column(String(50))

class Product(Base):
    __tablename__ = "products"

    product_id = Column(Integer, primary_key=True)
    product_name = Column(String(255))
    description = Column(String(255))
    category = Column(String(255))
    price = Column(Numeric(10, 2))
    stock_level = Column(Integer)
    image_url = Column(String(255))


class Order(Base):
    __tablename__ = "orders"

    order_id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.customer_id"))
    order_date = Column(DateTime)
    order_status = Column(String(50))
    total_amount = Column(Numeric(10, 2))


class Order_Items(Base):
    __tablename__ = "order_items"

    order_item_id = Column(Integer, primary_key=True)
    order_id = Column(Integer, ForeignKey("orders.order_id"))
    product_id = Column(Integer, ForeignKey("products.product_id"))
    quantity = Column(Integer)
    unit_price = Column(Numeric(10, 2))


class Payments(Base):
    __tablename__ = "payments"

    payment_id = Column(Integer, primary_key=True)
    order_id = Column(Integer, ForeignKey("orders.order_id"))
    payment_method = Column(String(50))
    payment_date = Column(DateTime)
    transaction_id = Column(String(255))


class Reviews(Base):
    __tablename__ = "reviews"

    review_id = Column(Integer, primary_key=True)
    customer_id = Column(Integer, ForeignKey("customers.customer_id"))
    product_id = Column(Integer, ForeignKey("products.product_id"))
    rating = Column(Integer)
    review_text = Column(String(255))
    review_date = Column(DateTime)


# Create tables (drop existing if needed)
# Base.metadata.reflect(engine)
# if "customers" in Base.metadata.tables:
#     Base.metadata.tables["customers"].drop(engine)
# Base.metadata.create_all(engine)

Base.metadata.drop_all(engine)  # Drop all tables before creating them
Base.metadata.create_all(engine)

# Generate fake data
fake = Faker()
session = sessionmaker(bind=engine)()

for _ in range(10):
    customer = Customer(
        first_name=fake.first_name(),
        last_name=fake.last_name(),
        email=fake.email(),
        phone_number=fake.phone_number(),
        address_line_1=fake.street_address(),
        address_line_2=fake.secondary_address(),
        city=fake.city(),
        state=fake.state_abbr(),
        postal_code=fake.postcode(),
        country=fake.country(),
    )
    session.add(customer)

session.commit()

# Generate and insert fake data for Products
fake = Faker()
categories = ["Electronics", "Clothing", "Home & Garden", "Beauty", "Books"]

for _ in range(20):  # Generate 20 products
    product = Product(
        product_name=fake.word(),
        description=fake.text(),
        category=random.choice(categories),
        price=round(fake.pydecimal(min_value=10, max_value=100, positive=True), 2),
        stock_level=random.randint(10, 100),
        image_url=fake.image_url(),
    )
    session.add(product)

session.commit()



# Query data to pandas dataframe
session = sessionmaker(bind=engine)()
customers_df = pd.read_sql_table("customers", engine)
products_df = pd.read_sql_table("products", engine)

<ipython-input-53-9faf566bcc77>:11: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [ ]:
customers_df

,customer_id,first_name,last_name,email,phone_number,address_line_1,address_line_2,city,state,postal_code,country
0,1,Steve,Harris,sreid@example.org,404-619-1799,096 Gomez Radial Apt. 787,Apt. 255,Lake Derrick,OR,37866,Morocco
1,2,Timothy,Cannon,qellis@example.com,708.604.4944x556,39633 Jeffrey Isle,Apt. 281,New Brandon,IL,93187,Ghana
2,3,Laura,Brooks,juliebaker@example.com,310-255-9399,6891 White Curve,Apt. 118,Paulaburgh,MO,65837,Palau
3,4,Carolyn,Wilson,singletonwilliam@example.net,2818238958,954 Hebert Corner,Apt. 234,Amyborough,KY,20982,Mali
4,5,Keith,Smith,kristinkoch@example.com,(876)273-3061,5162 Wallace Square,Suite 465,East Pamelaton,OR,47127,Chad
5,6,Maria,Nelson,brendaking@example.net,690-408-1918x40414,449 Abigail Causeway,Apt. 302,New Hollytown,FL,62905,Falkland Islands (Malvinas)
6,7,Cassie,Walker,barbara62@example.org,(722)566-2255x1590,7880 Jennifer Trace,Suite 272,West Christopherport,NM,39626,Indonesia
7,8,Richard,Potts,terrigarcia@example.org,(939)833-4456,226 Amber Point,Suite 686,Pereztown,KY,29918,Cape Verde
8,9,Frank,Wells,bradleyaustin@example.org,+1-926-917-1227x215,10077 Rowland Flat Apt. 649,Apt. 445,South Rachelland,DC,64265,Chile
9,10,Oscar,Adams,qjones@example.org,(753)473-8690,80658 Hull Light Suite 976,Suite 476,New Chris,ME,75955,Wallis and Futuna

In [ ]:
products_df

,product_id,product_name,description,category,price,stock_level,image_url
0,1,trade,Send student we town break get. Rest dog high ...,Electronics,76.03,42,https://placekitten.com/802/772
1,2,ever,Air area economy energy song figure profession...,Clothing,49.38,55,https://dummyimage.com/195x216
2,3,myself,Shake order development admit nation test deci...,Electronics,15.89,23,https://dummyimage.com/18x1009
3,4,little,Color structure personal line public he. Metho...,Electronics,25.12,13,https://dummyimage.com/681x913
4,5,thought,Job force new role answer field wish body. Gen...,Clothing,71.26,20,https://placekitten.com/856/715
5,6,statement,Themselves indeed under candidate. East view h...,Clothing,83.02,12,https://picsum.photos/698/750
6,7,white,Paper few economy although school often sell. ...,Clothing,11.19,28,https://dummyimage.com/592x486
7,8,kid,Strong job staff whom meeting because black. C...,Electronics,92.11,69,https://picsum.photos/985/716
8,9,responsibility,Join though notice senior might pattern beauti...,Books,43.74,31,https://picsum.photos/469/742
9,10,loss,Player ready we cut cause. Mrs against fall pl...,Clothing,43.05,54,https://placekitten.com/247/487
10,11,song,Section build production effort move close. Do...,Beauty,21.66,11,https://dummyimage.com/591x730
11,12,reflect,Stand show deep owner. Doctor brother more spa...,Books,29.03,15,https://dummyimage.com/724x480
12,13,ten,Term across cost blue result whom country. Tea...,Books,14.74,36,https://placekitten.com/423/609
13,14,agency,Doctor under evening. Somebody hospital includ...,Electronics,97.34,71,https://dummyimage.com/96x973
14,15,wall,City thought different option strong allow wea...,Clothing,63.97,89,https://dummyimage.com/885x8
15,16,country,Dinner skill my weight. Especially stock long ...,Electronics,20.96,23,https://placekitten.com/511/379
16,17,ten,Marriage magazine recently your. Position huma...,Electronics,80.33,69,https://placekitten.com/948/522
17,18,throw,Capital policy can leave part coach kid. From ...,Home & Garden,93.37,89,https://dummyimage.com/183x284
18,19,sister,Short any their cell. Debate economy huge whet...,Home & Garden,89.63,18,https://placekitten.com/819/549
19,20,this,Dinner book summer. Statement business take bo...,Beauty,77.04,77,https://placekitten.com/230/149